# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ebiznesbackend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/jakub-danielewicz/ebiznes-backend:latest/
        username: ${{ secrets.AzureAppService_ContainerUsername_51bf73e416c447db8d86bf49abaff1cc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0768214a14454b86b8455799c285f23c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/jakub-danielewicz/ebiznes-backend:latest/${{ secrets.AzureAppService_ContainerUsername_51bf73e416c447db8d86bf49abaff1cc }}/ebiznes-backend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ebiznesbackend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d6fe8919106d4673a3730c56e311424b }}
        images: 'ghcr.io/jakub-danielewicz/ebiznes-backend:latest/${{ secrets.AzureAppService_ContainerUsername_51bf73e416c447db8d86bf49abaff1cc }}/ebiznes-backend:${{ github.sha }}'