name: Build, Test & Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Set lowercase owner
        id: lcowner
        run: |
          echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./zadanie_cypress/backend
          file: ./zadanie_cypress/backend/Dockerfile
          push: true
          tags: ghcr.io/${{ steps.lcowner.outputs.owner }}/ebiznes-backend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./zadanie_cypress/frontend
          file: ./zadanie_cypress/frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ steps.lcowner.outputs.owner }}/ebiznes-frontend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ebiznesbackend'
          publish-profile: ${{ secrets.BACKEND_PUBLISH_PROFILE }}
          images: ghcr.io/jakub-danielewicz/ebiznes-backend:latest

      - name: Deploy frontend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ebiznesfrontend'
          publish-profile: ${{ secrets.FRONTEND_PUBLISH_PROFILE }}
          images: ghcr.io/jakub-danielewicz/ebiznes-frontend:latest

  # cypress-tests:
  #   needs: deploy
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 20

  #     - name: Install dependencies
  #       run: cd zadanie_cypress/frontend && npm ci

  #     - name: Run Cypress tests
  #       run: cd zadanie_cypress/frontend && npx cypress run
